-- Apti database schema
-- Run once against your PostgreSQL database:
--   psql $DATABASE_URL -f schema.sql

-- Enable pgcrypto for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ─── Skills (the 8 chapters) ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS skills (
    id          TEXT PRIMARY KEY,           -- 'arithmetic', 'algebra', etc.
    num         TEXT        NOT NULL,       -- 'I', 'II', etc.
    label       TEXT        NOT NULL,
    accent_key  TEXT        NOT NULL,       -- maps to frontend theme key
    locked      BOOLEAN     NOT NULL DEFAULT true,
    sort_order  INTEGER     NOT NULL
);

-- ─── Sub-skills (sections within each chapter) ────────────────────────────────
CREATE TABLE IF NOT EXISTS sub_skills (
    id          SERIAL PRIMARY KEY,
    skill_id    TEXT        NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    label       TEXT        NOT NULL,
    sort_order  INTEGER     NOT NULL
);

-- ─── Mastery scores ───────────────────────────────────────────────────────────
-- One row per (skill, sub_skill) pair. sub_skill_id NULL = chapter-level score.
CREATE TABLE IF NOT EXISTS mastery (
    id              SERIAL PRIMARY KEY,
    skill_id        TEXT        NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    sub_skill_id    INTEGER     REFERENCES sub_skills(id) ON DELETE CASCADE,
    score           INTEGER     NOT NULL DEFAULT 0 CHECK (score >= 0 AND score <= 100),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (skill_id, sub_skill_id)
);

-- ─── Study sessions ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sessions (
    id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    skill_id        TEXT        NOT NULL REFERENCES skills(id),
    sub_skill_id    INTEGER     REFERENCES sub_skills(id),
    topic           TEXT        NOT NULL,
    lesson_json     JSONB,                  -- Lecturer output, stored verbatim
    started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at    TIMESTAMPTZ
);

-- ─── Questions generated by the Examiner ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS session_questions (
    id              TEXT        PRIMARY KEY,    -- id from Examiner JSON
    session_id      UUID        NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    layer           TEXT        NOT NULL CHECK (layer IN ('recognise', 'apply', 'reason')),
    type            TEXT        NOT NULL CHECK (type IN ('mcq', 'open')),
    prompt          TEXT        NOT NULL,
    options         JSONB,                      -- array of strings, null for open
    correct_index   INTEGER,                    -- null for open questions
    model_answer    TEXT,                       -- null for MCQ
    explanation     TEXT        NOT NULL
);

-- ─── Submitted answers ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS session_answers (
    id              SERIAL      PRIMARY KEY,
    session_id      UUID        NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    question_id     TEXT        NOT NULL REFERENCES session_questions(id),
    value           TEXT        NOT NULL,       -- index string (MCQ) or free text (open)
    response_time_ms INTEGER,
    -- MCQ grading (done in code)
    is_correct      BOOLEAN,
    -- Open answer grading (from Grader LLM)
    intuition       NUMERIC(4,3),               -- 0.000 – 1.000
    method_score    NUMERIC(4,3),
    accuracy        NUMERIC(4,3),
    verdict         TEXT CHECK (verdict IN ('mastered', 'fragile', 'misunderstood')),
    feedback        TEXT
);

-- ─── Flashcards ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS cards (
    id              TEXT        PRIMARY KEY,    -- id from Cartographer JSON
    skill_id        TEXT        NOT NULL REFERENCES skills(id),
    front           TEXT        NOT NULL,
    back            TEXT        NOT NULL,
    -- SM-2 state
    interval_days   INTEGER     NOT NULL DEFAULT 1,
    ease_factor     NUMERIC(4,2) NOT NULL DEFAULT 2.50,
    due_date        DATE        NOT NULL DEFAULT CURRENT_DATE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── Flashcard review log ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS card_reviews (
    id              SERIAL      PRIMARY KEY,
    card_id         TEXT        NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
    grade           INTEGER     NOT NULL CHECK (grade IN (0, 1, 2)),  -- 0=forgot,1=partial,2=mastered
    reviewed_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    interval_days   INTEGER     NOT NULL,       -- interval assigned after this review
    new_due_date    DATE        NOT NULL
);

-- ─── Seed: the 8 chapters ─────────────────────────────────────────────────────
INSERT INTO skills (id, num, label, accent_key, locked, sort_order) VALUES
    ('arithmetic', 'I',    'Arithmetic & Number Sense', 'green',  false, 1),
    ('algebra',    'II',   'Algebra',                   'accent', false, 2),
    ('trig',       'III',  'Trigonometry',              'gold',   false, 3),
    ('vectors',    'IV',   'Vectors & Geometry',        'blue',   false, 4),
    ('calculus',   'V',    'Calculus',                  'accent', true,  5),
    ('linalg',     'VI',   'Linear Algebra',            'blue',   true,  6),
    ('diffeq',     'VII',  'Differential Equations',    'gold',   true,  7),
    ('prob',       'VIII', 'Probability & Statistics',  'green',  true,  8)
ON CONFLICT (id) DO NOTHING;

-- Seed sub-skills
INSERT INTO sub_skills (skill_id, label, sort_order) VALUES
    ('arithmetic', 'Fractions',     1),
    ('arithmetic', 'Ratios',        2),
    ('arithmetic', 'Percentages',   3),
    ('arithmetic', 'Number Systems',4),
    ('algebra',    'Variables',     1),
    ('algebra',    'Equations',     2),
    ('algebra',    'Functions',     3),
    ('algebra',    'Logarithms',    4),
    ('trig',       'Unit Circle',   1),
    ('trig',       'Trig Functions',2),
    ('trig',       'Identities',    3),
    ('trig',       'Waves',         4),
    ('vectors',    '2D/3D Space',   1),
    ('vectors',    'Dot Product',   2),
    ('vectors',    'Cross Product', 3),
    ('vectors',    'Transforms',    4),
    ('calculus',   'Limits',        1),
    ('calculus',   'Derivatives',   2),
    ('calculus',   'Integrals',     3),
    ('calculus',   'Applications',  4),
    ('linalg',     'Matrices',      1),
    ('linalg',     'Eigenvalues',   2),
    ('linalg',     'Systems',       3),
    ('linalg',     'Transforms',    4),
    ('diffeq',     'ODEs',          1),
    ('diffeq',     'PDEs',          2),
    ('diffeq',     'Modelling',     3),
    ('diffeq',     'Laplace',       4),
    ('prob',       'Distributions', 1),
    ('prob',       'Inference',     2),
    ('prob',       'Bayes',         3),
    ('prob',       'Data',          4)
ON CONFLICT DO NOTHING;

-- Seed chapter-level mastery rows (score=0 to start)
INSERT INTO mastery (skill_id, sub_skill_id, score)
SELECT id, NULL, 0 FROM skills
ON CONFLICT (skill_id, sub_skill_id) DO NOTHING;
